heat_template_version: 2016-04-08

description: "Dynamic Sized TSE Demo Stack"

parameter_groups:
  - label: "Credentials"
    description: "Required information for accessing the stack"
    parameters:
      - access_key_name
  - label: "Agent nodes"
    description: "Stack size; how many of each type of agent to deploy"
    parameters:
      - count_agents_centos7
      - count_agents_windows
      - count_agents_centos6
      - count_agents_ubuntu1404
  - label: "Advanced"
    description: "Parameters for advanced adjustment of the stack. You should not need to adjust these."
    parameters:
      - network_private
      - network_public

parameters:
  access_key_name:
    type: string
    description: Name of keypair to assign to servers
    constraints:
      - { custom_constraint: nova.keypair }
  pe_demo_build_url:
    type: string
    label: "PE Demo Build URL"
    description: URL to download pe-demo build tarball from
    default: http://tse-builds.s3-us-west-2.amazonaws.com/2017.1.x/releases/pe-demo-latest.tar.gz
  pe_source_url:
    type: string
    label: "PE Source URL"
    description: URL to download Puppet Enterprise from (tar.gz or tar)
    default: http://pe-releases.puppetlabs.net/2017.1.1/puppet-enterprise-2017.1.1-el-7-x86_64.tar.gz
  count_agents_centos7:
    type: number
    label: "Number of CentOS 7 agents"
    default: 0
  count_agents_centos6:
    type: number
    label: "Number of CentOS 6 agents"
    default: 0
  count_agents_ubuntu1404:
    type: number
    label: "Number of Ubuntu 14.04 agents"
    default: 0
  count_agents_windows:
    type: number
    label: "Number of Windows Server 2012 R2 agents"
    default: 0
  network_private:
    type: string
    label: "Private Network"
    description: The name of the private network you wish to attach this stack too
    default: network0
    constraints:
      #- { custom_constraint: neutron.network }
  network_public:
    type: string
    label: "Public Network"
    description: The name of the network to source public floaiting IPs from
    default: ext-net-pdx1-opdx1
    constraints:
      #- { custom_constraint: neutron.network }

resources:

  name_nonce:
    type: OS::Heat::RandomString
    properties:
      length: 8
      sequence: lowercase

  master_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_private }
      security_groups: ["sg0"]

  master_floating_ip_association:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: network_public }
      port_id: { get_resource: master_port }

  master_server:
    type: OS::Nova::Server
    properties:
      name: "master.inf.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "m1.medium"
      key_name: { get_param: access_key_name }
      networks:
        - port: { get_resource: master_port }
      user_data:
        str_replace:
          template:
            get_file: "https://raw.githubusercontent.com/reidmv/tse-stack-slice/master/user_data/bootstrap-master"
          params:
            $gitlab_floating_ip: { get_attr: [gitlab_floating_ip_association, floating_ip_address] }
            $pe_demo_build_url: { get_param: pe_demo_build_url }
            $pe_source_url: { get_param: pe_source_url }
            $wc_notify: { get_attr: ['master_wait_handle', 'curl_cli'] }

  master_wait:
    type: "OS::Heat::WaitCondition"
    depends_on: master_server
    properties:
      handle:
        get_resource: master_wait_handle
      timeout: 2400
      count: 1

  master_wait_handle:
    type: "OS::Heat::WaitConditionHandle"

  gitlab_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_private }
      security_groups: ["sg0"]

  gitlab_floating_ip_association:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: network_public }
      port_id: { get_resource: gitlab_port }

  gitlab_server:
    type: OS::Nova::Server
    depends_on: master_wait
    properties:
      name: "gitlab.inf.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "m1.medium"
      key_name: { get_param: access_key_name }
      networks:
        - port: { get_resource: gitlab_port }
      user_data:
        str_replace:
          template:
            get_file: "https://raw.githubusercontent.com/reidmv/tse-stack-slice/master/user_data/bootstrap-agent-linux"
          params:
            $master_ip: { get_attr: [master_server, first_address] }

  centos7_agents:
    type: OS::Heat::ResourceGroup
    depends_on: master_wait
    properties:
      count: { get_param: count_agents_centos7 }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: "centos_7_x86_64"
          flavor: "g1.medium"
          key_name: { get_param: access_key_name }
          name: "centos-7-%index%.pdx.puppet.vm"
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://raw.githubusercontent.com/reidmv/tse-stack-slice/master/user_data/bootstrap-agent-linux"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

  centos6_agents:
    type: OS::Heat::ResourceGroup
    depends_on: master_wait
    properties:
      count: { get_param: count_agents_centos6 }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: "6ed7eb41-ae01-4f7f-8294-36e86e045bb6"
          flavor: "g1.medium"
          key_name: { get_param: access_key_name }
          name: "centos-6-%index%.pdx.puppet.vm"
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://raw.githubusercontent.com/reidmv/tse-stack-slice/master/user_data/bootstrap-agent-linux"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

  ubuntu1404_agents:
    type: OS::Heat::ResourceGroup
    depends_on: master_wait
    properties:
      count: { get_param: count_agents_ubuntu1404 }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: "ubuntu_14.04_x86_64"
          flavor: "g1.medium"
          key_name: { get_param: access_key_name }
          name: "ubuntu-1404-%index%.pdx.puppet.vm"
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://raw.githubusercontent.com/reidmv/tse-stack-slice/master/user_data/bootstrap-agent-linux"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

  windows_agents:
    type: OS::Heat::ResourceGroup
    depends_on: master_wait
    properties:
      count: { get_param: count_agents_windows }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: "windows_2012_r2_std_eval_x86_64"
          flavor: "g1.large"
          key_name: { get_param: access_key_name }
          name: "win-2012-%index%.pdx.puppet.vm"
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://raw.githubusercontent.com/reidmv/tse-stack-slice/master/user_data/bootstrap-agent-windows"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

outputs:
  master_ip:
    description: The IP address of the Puppet master server
    value: { get_attr: [master_floating_ip_association, floating_ip_address] }
  gitlab_ip:
    description: The IP address of the Gitlab server
    value: { get_attr: [gitlab_floating_ip_association, floating_ip_address] }
