heat_template_version: 2015-04-30

description: "TSE PE Demo Stack"

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    constraints:
      - { custom_constraint: nova.keypair }
  pe_demo_build_url:
    type: string
    label: "PE Demo Build URL"
    description: URL to download pe-demo build tarball from
    default: http://tse-builds.s3-us-west-2.amazonaws.com/2016.4.x/releases/pe-demo-latest.tar.gz
  pe_source_url:
    type: string
    label: "PE Source URL"
    description: URL to download Puppet Enterprise from (tar.gz or tar)
    default: http://pe-releases.puppetlabs.net/2016.4.0/puppet-enterprise-2016.4.0-el-7-x86_64.tar.gz
  centos7_agent_count:
    type: number
    label: "Number of Centos 7 agents"
    default: 0

resources:

  name_nonce:
    type: OS::Heat::RandomString
    properties:
      length: 8
      sequence: lowercase

  master_server:
    type: OS::Nova::Server
    properties:
      name: "master.inf.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "m1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data_format: RAW
      user_data:
        str_replace:
          template:
            get_file: "https://github.com/reidmv/tse-stack-slice/tree/master/user_data/bootstrap-master"
          params:
            $gitlab_floating_ip: { get_attr: [gitlab_floating_ip, ip] }
            $pe_demo_build_url: { get_param: pe_demo_build_url }
            $pe_source_url: { get_param: pe_source_url }
            $wc_notify: { get_attr: ['master_server_wait_handle', 'curl_cli'] }

  master_server_wait:
    type: "OS::Heat::WaitCondition"
    depends_on: master_server
    properties:
      handle:
        get_resource: master_server_wait_handle
      timeout: 2400
      count: 1

  master_server_wait_handle:
    type: "OS::Heat::WaitConditionHandle"

  master_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  master_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: master_floating_ip }
      server_id: { get_resource: master_server }

  gitlab_server:
    type: OS::Nova::Server
    depends_on: master_server_wait
    properties:
      name: "gitlab.inf.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "m1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        str_replace:
          template:
            get_file: "https://github.com/reidmv/tse-stack-slice/tree/master/user_data/bootstrap-agent-linux"
          params:
            $master_ip: { get_attr: [master_server, first_address] }

  gitlab_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  gitlab_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: gitlab_floating_ip }
      server_id: { get_resource: gitlab_server }

  centos7_agents:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: centos7_agent_count }
      resource_def:
        type: OS::Nova::Server
        depends_on: master_server_wait
        properties:
          image: "centos_7_x86_64"
          flavor: "g1.medium"
          key_name: { get_param: key_name }
          name:
            str_replace:
              template: "centos-$nonce.pdx.puppet.vm"
              params:
                $nonce: { get_resource: name_nonce }
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://github.com/reidmv/tse-stack-slice/tree/master/user_data/bootstrap-agent-linux"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

  centos7_agents:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        depends_on: master_server_wait
        properties:
          image: "centos_7_x86_64"
          flavor: "g1.medium"
          key_name: { get_param: key_name }
          name:
            str_replace:
              template: "centos-7-$nonce.pdx.puppet.vm"
              params:
                $nonce: { get_resource: name_nonce }
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://github.com/reidmv/tse-stack-slice/tree/master/user_data/bootstrap-agent-linux"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

  centos6_agents:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        depends_on: master_server_wait
        properties:
          image: "6ed7eb41-ae01-4f7f-8294-36e86e045bb6"
          flavor: "g1.medium"
          key_name: { get_param: key_name }
          name:
            str_replace:
              template: "centos-6-$nonce.pdx.puppet.vm"
              params:
                $nonce: { get_resource: name_nonce }
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://github.com/reidmv/tse-stack-slice/tree/master/user_data/bootstrap-agent-linux"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

  ubuntu1404_agents:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        depends_on: master_server_wait
        properties:
          image: "ubuntu_14.04_x86_64"
          flavor: "g1.medium"
          key_name: { get_param: key_name }
          name:
            str_replace:
              template: "ubuntu-1404-$nonce.pdx.puppet.vm"
              params:
                $nonce: { get_resource: name_nonce }
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://github.com/reidmv/tse-stack-slice/tree/master/user_data/bootstrap-agent-linux"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

  windows_agents:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        depends_on: master_server_wait
        properties:
          image: "windows_2012_r2_std_eval_x86_64"
          flavor: "g1.large"
          key_name: { get_param: key_name }
          name:
            str_replace:
              template: "win-2012-$nonce.pdx.puppet.vm"
              params:
                $nonce: { get_resource: name_nonce }
          security_groups:
            - "sg0"
          user_data:
            str_replace:
              template:
                get_file: "https://github.com/reidmv/tse-stack-slice/tree/master/user_data/bootstrap-agent-windows"
              params:
                $master_ip: { get_attr: [master_server, first_address] }

outputs:
  master_ip:
    description: The IP address of the Puppet master server
    value: { get_attr: [master_floating_ip, ip] }
  gitlab_ip:
    description: The IP address of the Gitlab server
    value: { get_attr: [gitlab_floating_ip, ip] }
