#!/bin/bash
#
# Template parameters
#   - $master_ip
#
echo $master_ip master.inf.puppet.vm >> /etc/hosts
hostname $(curl http://169.254.169.254/latest/meta-data/local-hostname)
echo $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) $(hostname) >> /etc/hosts
curl -k https://master.inf.puppet.vm:8140/packages/current/install.bash | bash
